{
 "title": "Application Dashboard",
 "description": "Istio Mesh Dashboard version 1.17.8",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "lokidatasource", "query": "loki" },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(caretta_links_observed)"
    }
   },
   {
    "name": "kind",
    "query": {
     "query": "query_result(caretta_links_observed)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "query_result(caretta_links_observed)"
    }
   },
   { "name": "port", "label": "server port", "query": { "query": "label_values(server_port)" } }
  ]
 },
 "panels": [
  {
   "title": "Service Map ☸️",
   "type": "nodeGraph",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase((sum by (id, title, subTitle, detail__kind, arc__color) (label_replace((label_replace(label_replace(label_replace(label_replace((caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\"} or caretta_links_observed{server_namespace=~\"$namespace\", server_kind=~\"$kind\", server_name=~\"$workload\", server_port=~\"$port\"}), \"detail__kind\", \"$1\", \"server_kind\", \"(.*)\"), \"subTitle\", \"$1\", \"server_namespace\", \"(.*)\"), \"title\", \"$1\", \"server_name\", \"(.*)\"), \"id\", \"$1\", \"server_id\", \"(.*)\") or label_replace(label_replace(label_replace(label_replace((caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\"} or caretta_links_observed{server_namespace=~\"$namespace\", server_kind=~\"$kind\", server_name=~\"$workload\", server_port=~\"$port\"}), \"detail__kind\", \"$1\", \"client_kind\", \"(.*)\"), \"subTitle\", \"$1\", \"client_namespace\", \"(.*)\"), \"title\", \"$1\", \"client_name\", \"(.*)\"), \"id\", \"$1\", \"client_id\", \"(.*)\")  ), \"arc__color\", \"1\", \"link_id\", \"(.*)\")) )[$__range:$__interval])  > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase((sum by (id, source, target, mainStat) ((label_replace(label_replace(label_replace(label_replace((caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\"} or caretta_links_observed{server_namespace=~\"$namespace\", server_kind=~\"$kind\", server_name=~\"$workload\", server_port=~\"$port\"}), \"id\", \"$1\", \"link_id\", \"(.*)\"), \"source\", \"$1\", \"client_id\", \"(.*)\"), \"target\", \"$1\", \"server_id\", \"(.*)\"), \"mainStat\", \"$1\", \"server_port\", \"(.*)\"))) )[$__range:$__interval]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Request Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"source\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Virtual Services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"VirtualService\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"VirtualService\", event=\"delete\"}) or max(up * 0))"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", response_code=~\"4.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Global Success Rate (non-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"source\", response_code!~\"5.*\"}[1m])) / sum(rate(istio_requests_total{reporter=\"source\"}[1m]))"
    }
   ]
  },
  {
   "title": "Gateways",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"Gateway\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"Gateway\", event=\"delete\"}) or max(up * 0))"
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", response_code=~\"5.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Destination Rules",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"DestinationRule\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"DestinationRule\", event=\"delete\"}) or max(up * 0))"
    }
   ]
  },
  {
   "title": "Non-2xx Responses by Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(istio_requests_total{reporter=\"source\" ,response_code!=\"200\"}[1m])",
     "legendFormat": "{{destination_service_name}} ->{{source_app}}"
    }
   ]
  },
  {
   "title": "HTTP/GRPC Workloads",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "label_join(sum(rate(istio_requests_total{reporter=\"source\", response_code=\"200\"}[1m])) by (destination_workload, destination_workload_namespace, destination_service), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((sum(rate(istio_requests_total{reporter=\"source\", response_code!~\"5.*\"}[1m])) by (destination_workload, destination_workload_namespace) / sum(rate(istio_requests_total{reporter=\"source\"}[1m])) by (destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    }
   ]
  },
  {
   "title": "Service error counts per min",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate({k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"web-.*\"} |~ `(?i)error` [1m]))",
     "legendFormat": "{{web}}"
    },
    {
     "expr": "sum(rate({k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"catalogue-.*\"} |~ `(?i)error` [1m]))",
     "legendFormat": "{{catalogue}}"
    },
    {
     "expr": "sum(rate({k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"user-.*\"} |~ `(?i)error` [1m]))"
    },
    {
     "expr": "sum(rate({k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"cart-.*\"} |~ `(?i)error` [1m]))"
    },
    {
     "expr": "sum(rate({k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"payment-.*\"} |~ `(?i)error` [1m]))",
     "legendFormat": "{{payment}}"
    },
    {
     "expr": "sum(rate({k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"dispatch-.*\"} |~ `(?i)error` [1m]))",
     "legendFormat": "{{dispatch}}"
    },
    {
     "expr": "sum(rate({k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"shipping-.*\"} |~ `(?i)error` [1m]))",
     "legendFormat": "{{shipping}}"
    },
    {
     "expr": "sum(rate({k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"ratings-.*\"} |~ `(?i)error` [1m]))",
     "legendFormat": "{{ratings}}"
    }
   ]
  },
  {
   "title": "Web Service Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"web-.*\"} |~ `(?i)error`"
    }
   ]
  },
  {
   "title": "Ratings Service  Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"ratings-.*\"} |~ `(?i)error`"
    }
   ]
  },
  {
   "title": "P90 latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_join((histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[5m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[5m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{destination_workload_var}}"
    }
   ]
  },
  {
   "title": "Dispatch Service Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"dispatch-.*\"} |~ `(?i)error`"
    }
   ]
  },
  {
   "title": "Shipping Service Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "{k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"shipping-.*\"} |~ `(?i)error`"
    }
   ]
  },
  {
   "title": "P50 latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_join((histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[5m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[5m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{destination_workload_var}}"
    }
   ]
  },
  {
   "title": "Cart Service Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "{k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"cart-.*\"} |~ `(?i)error`"
    }
   ]
  },
  {
   "title": "Catalogue Service Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "{k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"catalogue-.*\"} |~ `(?i)error`"
    }
   ]
  },
  {
   "title": "Payment Service Error Logs ",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "{k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"payment-.*\"} |~ `(?i)error`"
    }
   ]
  },
  {
   "title": "User Service Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "{k8s_namespace_name=\"robot-shop\", k8s_pod_name=~\"user-.*\"} |~ `(?i)error`"
    }
   ]
  }
 ]
}