#!/usr/bin/env bash
# Fails when the Spec Kit artifacts committed under .specify/ and the harness
# skill folders were generated by a different spec-kit release than the one
# `make install` pins (SPEC_KIT_VERSION in infra/scripts/dev/install-deps.sh).
# Otherwise a fresh machine's `specify integration upgrade` silently rewrites
# scripts, templates and skills that CI and the docs assume.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
INSTALLER="$ROOT/infra/scripts/dev/install-deps.sh"

if ! command -v jq >/dev/null 2>&1; then
  echo "speckit-version: jq not found — skipping"
  [ "${STRICT:-0}" = "1" ] && exit 1
  exit 0
fi

pin="$(sed -n 's/^SPEC_KIT_VERSION="v\{0,1\}\([^"]*\)"$/\1/p' "$INSTALLER")"
if [ -z "$pin" ]; then
  echo "speckit-version: SPEC_KIT_VERSION not found in $INSTALLER"
  exit 1
fi

status=0
check() {
  local file="$1" got="$2"
  if [ "$got" != "$pin" ]; then
    echo "speckit-version: $file was generated by spec-kit $got; installer pins v$pin"
    status=1
  fi
}

check .specify/integration.json "$(jq -r '.version // empty' "$ROOT/.specify/integration.json")"
check .specify/init-options.json "$(jq -r '.speckit_version // empty' "$ROOT/.specify/init-options.json")"
for m in "$ROOT"/.specify/integrations/*.manifest.json; do
  check ".specify/integrations/$(basename "$m")" "$(jq -r '.version // empty' "$m")"
done

if [ "$status" -ne 0 ]; then
  echo "  Re-run: for k in \$(jq -r '.installed_integrations[]' .specify/integration.json); do specify integration upgrade \$k --force; done && agent/tools/loom.sh"
  echo "  or change SPEC_KIT_VERSION in $INSTALLER to match, then commit both."
  exit 1
fi
echo "speckit-version: artifacts match installer pin v$pin"
