#!/usr/bin/env bash
# loom — emit harness adapters from the canonical Claude Code config.
#
# Phase B of the loom design (see ~/claude-plans/loom.md and
# intent/loom.md): deterministic translation, no network, no model.
# One input -> byte-identical output. `--check` diffs regeneration
# against the committed adapters and exits 1 on any drift.
#
# Emitters live in lib/emit-<harness>.sh — a drop-in registry (D7).
# Adding a harness = one emitter file + one spec pack, no core changes.

set -euo pipefail

LOOM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${LOOM_DIR}/../.." && pwd)"
CONFIG="${LOOM_DIR}/loom.config.json"

usage() {
  cat <<'EOF'
usage: loom.sh [--check] [harness ...]

  (no args)      emit adapters into the repo (apply mode)
  --check        emit into a temp dir and diff against committed files;
                 exit 1 with the diff on any drift
  harness ...    restrict to named harness(es), e.g. `loom.sh devin`
EOF
}

[[ "${1:-}" == "-h" || "${1:-}" == "--help" ]] && { usage; exit 0; }
CHECK=0
if [[ "${1:-}" == "--check" ]]; then
  CHECK=1
  shift
fi
HARNESSES=("$@")

# ---------------------------------------------------------------- allowlist
# Hard gate (plan 3.3 rule 4): every MCP server in the canonical config must
# be approved in the policy file. Loom must not be a way around the policy.
ALLOWLIST="${REPO_ROOT}/agent/policies/allowed-mcp-servers.md"
for server in $(jq -r '.mcpServers | keys[]' "${REPO_ROOT}/.mcp.json"); do
  if ! grep -q "^\s*[-|].*\b${server}\b" "${ALLOWLIST}"; then
    echo "loom: ERROR: MCP server '${server}' is not approved in ${ALLOWLIST#"$REPO_ROOT"/}" >&2
    exit 1
  fi
done

# ---------------------------------------------------------------- IR
# Normalize canonical config to an intermediate representation (plan 3.2).
IR="$(mktemp -d)"
trap 'rm -rf "${IR}"' EXIT

jq -n \
  --slurpfile mcp "${REPO_ROOT}/.mcp.json" \
  --slurpfile settings "${REPO_ROOT}/.claude/settings.json" \
  --slurpfile overrides "${CONFIG}" \
  '
  {
    mcp: [$mcp[0].mcpServers | to_entries[] |
      { name: .key, type: .value.type, url: .value.url,
        overrides: $overrides[0].mcp_overrides }],
    permissions: $settings[0].permissions,
    hooks: $settings[0].hooks,
    context: $overrides[0].paths.canonical_context
  }' > "${IR}/ir.json"

# ---------------------------------------------------------------- emitters
OUT="${IR}/out"
mkdir -p "${OUT}"

collect_emitters() {
  local f name
  for f in "${LOOM_DIR}"/lib/emit-*.sh; do
    # shellcheck disable=SC1090
    source "${f}"
    name="$(basename "${f}" .sh)"
    name="${name#emit-}"
    if [[ ${#HARNESSES[@]} -eq 0 ]]; then
      EMITTERS+=("${name}")
    else
      for h in "${HARNESSES[@]}"; do
        [[ "${name}" == "${h}" ]] && EMITTERS+=("${name}")
      done
    fi
  done
}

EMITTERS=()
collect_emitters
if [[ ${#EMITTERS[@]} -eq 0 ]]; then
  echo "loom: no emitters matched: ${HARNESSES[*]:-<all>}" >&2
  exit 1
fi

# Gaps ledger (plan 3.3 rule 1): emitters append a row for every IR node
# they cannot express. Silent loss is the failure mode; this makes it loud.
GAPS_FILE="${OUT}/agent/harness-specs/GAPS.md"
mkdir -p "$(dirname "${GAPS_FILE}")"
cat > "${GAPS_FILE}" <<'EOF'
<!-- generated by loom — do not edit by hand -->
# Harness capability gaps

Anything an emitter could not express from the IR, with the compensating
control. Empty table = the canonical config is fully representable.

| Harness | Dropped node | Compensating control |
|---------|--------------|----------------------|
EOF

gap_add() {
  echo "| $1 | $2 | $3 |" >> "${GAPS_FILE}"
}

for h in "${EMITTERS[@]}"; do
  "emit_${h}" "${IR}/ir.json" "${OUT}"
done

# Spec-pack staleness (plan 3.4): warn, never fail — refresh is Phase A's call.
for pack in "${REPO_ROOT}"/agent/harness-specs/*.md; do
  gen="$(sed -n 's/^generated: //p' "${pack}" | head -1)"
  [[ -z "${gen}" ]] && continue
  age=$(( ( $(date +%s) - $(date -d "${gen}" +%s) ) / 86400 ))
  if (( age > 30 )); then
    echo "loom: WARNING: spec pack ${pack##*/} is ${age} days old — run the loom skill to refresh" >&2
  fi
done

# ---------------------------------------------------------------- apply/check
if [[ ${CHECK} -eq 1 ]]; then
  drift=0
  while IFS= read -r -d '' f; do
    rel="${f#"${OUT}"/}"
    committed="${REPO_ROOT}/${rel}"
    if [[ ! -f "${committed}" ]]; then
      echo "loom: MISSING (not committed): ${rel}"
      drift=1
    elif ! diff -u "${committed}" "${f}" > "${IR}/diff"; then
      echo "loom: DRIFT in ${rel}:"; cat "${IR}/diff"
      drift=1
    fi
  done < <(find "${OUT}" -type f -print0)
  if [[ ${drift} -eq 1 ]]; then
    echo "loom: --check FAILED — regenerate with: agent/tools/loom.sh" >&2
    exit 1
  fi
  echo "loom: check clean — adapters match regeneration"
  exit 0
fi

while IFS= read -r -d '' f; do
  rel="${f#"${OUT}"/}"
  mkdir -p "${REPO_ROOT}/$(dirname "${rel}")"
  cp "${f}" "${REPO_ROOT}/${rel}"
done < <(find "${OUT}" -type f -print0)
echo "loom: emitted ${#EMITTERS[@]} adapter set(s) + GAPS.md"
