#!/usr/bin/env bash
# Codex emitter (loom registry — see ../loom.sh header).
# Spec pack: agent/harness-specs/codex.md

emit_codex() {
  local ir="$1" out="$2"
  local dir="${out}/.codex"
  mkdir -p "${dir}"

  {
    echo "# Codex project-scoped configuration. Loads only when the project is marked"
    echo "# trusted (see developers.openai.com/codex/config-advanced)."
    echo "# Generated by loom from .mcp.json — do not edit by hand; edit the canonical"
    echo "# config or agent/tools/loom.config.json and re-run agent/tools/loom.sh."
    echo "# MCP server allowlist source of truth: agent/policies/allowed-mcp-servers.md"
    echo "# All listed servers are read-only documentation services: tool calls are"
    echo "# pre-approved (no per-call confirmation) per the allowlist's Tier 1 rules."
    echo
    jq -r '.mcp[] |
      "[mcp_servers.\(.name)]\nurl = \"\(.url)\"\ndefault_tools_approval_mode = \"auto\"\n"' "${ir}"
  } > "${dir}/config.toml"

  # hooks: Codex has no hook mechanism — gap, not silence (plan 3.3 rule 1)
  while IFS= read -r event; do
    [[ -n "${event}" ]] && gap_add codex "hook event: ${event}" \
      "git pre-commit hooks + CI (same scripts, .githooks/ + .github/workflows/ci.yml)"
  done < <(jq -r '.hooks | keys[]' "${ir}")
}
